In [1]:
import pandas as pd

# Getting the Data

In [21]:
data = pd.read_csv('country_profile_variables.csv')

In [22]:
data

,country,Region,Surface area (km2),Population in thousands (2017),"Population density (per km2, 2017)","Sex ratio (m per 100 f, 2017)",GDP: Gross domestic product (million current US$),"GDP growth rate (annual %, const. 2005 prices)",GDP per capita (current US$),Economy: Agriculture (% of GVA),...,Mobile-cellular subscriptions (per 100 inhabitants).1,Individuals using the Internet (per 100 inhabitants),Threatened species (number),Forested area (% of land area),CO2 emission estimates (million tons/tons per capita),"Energy production, primary (Petajoules)",Energy supply per capita (Gigajoules),"Pop. using improved drinking water (urban/rural, %)","Pop. using improved sanitation facilities (urban/rural, %)",Net Official Development Assist. received (% of GNI)
0,Afghanistan,SouthernAsia,652864,35530,54.4,106.3,20270,-2.4,623.2,23.3,...,8.3,42,2.1,9.8/0.3,63,5,78.2/47.0,45.1/27.0,21.43,-99
1,Albania,SouthernEurope,28748,2930,106.9,101.9,11541,2.6,3984.2,22.4,...,63.3,130,28.2,5.7/2.0,84,36,94.9/95.2,95.5/90.2,2.96,-99
2,Algeria,NorthernAfrica,2381741,41318,17.3,102.0,164779,3.8,4154.1,12.2,...,38.2,135,0.8,145.4/3.7,5900,55,84.3/81.8,89.8/82.2,0.05,-99
3,American Samoa,Polynesia,199,56,278.2,103.6,-99,-99,-99.0,-99,...,-99,92,87.9,-99,-99,-99,100.0/100.0,62.5/62.5,-99,-99
4,Andorra,SouthernEurope,468,77,163.8,102.3,2812,0.8,39896.4,0.5,...,96.9,13,34.0,0.5/6.4,1,119,100.0/100.0,100.0/100.0,-99,-99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Wallis and Futuna Islands,Polynesia,142,12,84.1,93.4,-99,-99,-99.0,-99,...,9.0,89,41.6,~0.0/1.6,-99,26,-99,-99,-99,-99
225,Western Sahara,NorthernAfrica,266000,553,2.1,110.1,-99,-99,-99.0,-99,...,-99,49,2.7,-99,-99,-99,-99,-99,-99,-99
226,Yemen,WesternAsia,527968,28250,53.5,102.1,29688,-28.1,1106.4,14.7,...,25.1,298,1.0,22.7/0.9,668,12,72.0/46.5,92.5/34.1,2.99,-99
227,Zambia,EasternAfrica,752612,17094,23.0,98.5,21255,2.9,1311.1,8.2,...,21.0,88,65.6,4.5/0.3,374,26,85.6/51.3,55.6/35.7,3.96,-99
228,Zimbabwe,EasternAfrica,390757,16530,42.7,95.0,13893,1.1,890.4,13.0,...,16.4,89,37.2,12.0/0.8,482,30,97.0/67.3,49.3/30.8,6.00,-99

# Checking the type of columns

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 50 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   country                                                     229 non-null    object
 1   Region                                                      229 non-null    object
 2   Surface area (km2)                                          229 non-null    object
 3   Population in thousands (2017)                              229 non-null    int64
 4   Population density (per km2, 2017)                          229 non-null    float64
 5   Sex ratio (m per 100 f, 2017)                               229 non-null    float64
 6   GDP: Gross domestic product (million current US$)           229 non-null    int64
 7   GDP growth rate (annual %, const. 2005 prices)              229 non-null    object
 8   GDP per capita (current US$)                                229 non-null    float64
 9   Economy: Agriculture (% of GVA)                             229 non-null    object
 10  Economy: Industry (% of GVA)                                229 non-null    float64
 11  Economy: Services and other activity (% of GVA)             229 non-null    float64
 12  Employment: Agriculture (% of employed)                     229 non-null    object
 13  Employment: Industry (% of employed)                        229 non-null    object
 14  Employment: Services (% of employed)                        229 non-null    object
 15  Unemployment (% of labour force)                            229 non-null    object
 16  Labour force participation (female/male pop. %)             229 non-null    object
 17  Agricultural production index (2004-2006=100)               229 non-null    int64
 18  Food production index (2004-2006=100)                       229 non-null    int64
 19  International trade: Exports (million US$)                  229 non-null    object
 20  International trade: Imports (million US$)                  229 non-null    object
 21  International trade: Balance (million US$)                  229 non-null    object
 22  Balance of payments, current account (million US$)          229 non-null    object
 23  Population growth rate (average annual %)                   229 non-null    object
 24  Urban population (% of total population)                    229 non-null    float64
 25  Urban population growth rate (average annual %)             229 non-null    object
 26  Fertility rate, total (live births per woman)               229 non-null    object
 27  Life expectancy at birth (females/males, years)             229 non-null    object
 28  Population age distribution (0-14 / 60+ years, %)           229 non-null    object
 29  International migrant stock (000/% of total pop.)           229 non-null    object
 30  Refugees and others of concern to UNHCR (in thousands)      229 non-null    object
 31  Infant mortality rate (per 1000 live births                 229 non-null    object
 32  Health: Total expenditure (% of GDP)                        229 non-null    float64
 33  Health: Physicians (per 1000 pop.)                          229 non-null    object
 34  Education: Government expenditure (% of GDP)                229 non-null    object
 35  Education: Primary gross enrol. ratio (f/m per 100 pop.)    229 non-null    object
 36  Education: Secondary gross enrol. ratio (f/m per 100 pop.)  229 non-null    object
 37  Education: Tertiary gross enrol. ratio (f/m per 100 pop.)   229 non-null    object
 38  Seats held by women in national parliaments %               229 non-null    float64
 39  Mobile-cellular subscriptions (per 100 inhabitants)         229 non-null    object
 40  Mobile-cellular subscriptions (per 100 inhabitants).1       229 non-null    object
 41  Individuals using the Internet (per 100 inhabitants)        229 non-null    int64
 42  Threatened species (number)                                 229 non-null    object
 43  Forested area (% of land area)                              229 non-null    object
 44  CO2 emission estimates (million tons/tons per capita)       229 non-null    int64
 45  Energy production, primary (Petajoules)                     229 non-null    int64
 46  Energy supply per capita (Gigajoules)                       229 non-null    object
 47  Pop. using improved drinking water (urban/rural, %)         229 non-null    object
 48  Pop. using improved sanitation facilities (urban/rural, %)  229 non-null    object
 49  Net Official Development Assist. received (% of GNI)        229 non-null    int64
dtypes: float64(8), int64(8), object(34)
memory usage: 89.6+ KB

# Change data type of the columns to Float

In [24]:
# Convert columns to numeric
for col in data.columns[2:]:
    data[col] = pd.to_numeric(data[col], errors='coerce')

# Checking the type of columns to check if the previous code works fine

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 50 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   country                                                     229 non-null    object
 1   Region                                                      229 non-null    object
 2   Surface area (km2)                                          228 non-null    float64
 3   Population in thousands (2017)                              229 non-null    int64
 4   Population density (per km2, 2017)                          229 non-null    float64
 5   Sex ratio (m per 100 f, 2017)                               229 non-null    float64
 6   GDP: Gross domestic product (million current US$)           229 non-null    int64
 7   GDP growth rate (annual %, const. 2005 prices)              228 non-null    float64
 8   GDP per capita (current US$)                                229 non-null    float64
 9   Economy: Agriculture (% of GVA)                             228 non-null    float64
 10  Economy: Industry (% of GVA)                                229 non-null    float64
 11  Economy: Services and other activity (% of GVA)             229 non-null    float64
 12  Employment: Agriculture (% of employed)                     213 non-null    float64
 13  Employment: Industry (% of employed)                        213 non-null    float64
 14  Employment: Services (% of employed)                        213 non-null    float64
 15  Unemployment (% of labour force)                            213 non-null    float64
 16  Labour force participation (female/male pop. %)             14 non-null     float64
 17  Agricultural production index (2004-2006=100)               229 non-null    int64
 18  Food production index (2004-2006=100)                       229 non-null    int64
 19  International trade: Exports (million US$)                  224 non-null    float64
 20  International trade: Imports (million US$)                  228 non-null    float64
 21  International trade: Balance (million US$)                  228 non-null    float64
 22  Balance of payments, current account (million US$)          221 non-null    float64
 23  Population growth rate (average annual %)                   222 non-null    float64
 24  Urban population (% of total population)                    229 non-null    float64
 25  Urban population growth rate (average annual %)             226 non-null    float64
 26  Fertility rate, total (live births per woman)               223 non-null    float64
 27  Life expectancy at birth (females/males, years)             12 non-null     float64
 28  Population age distribution (0-14 / 60+ years, %)           3 non-null      float64
 29  International migrant stock (000/% of total pop.)           0 non-null      float64
 30  Refugees and others of concern to UNHCR (in thousands)      199 non-null    float64
 31  Infant mortality rate (per 1000 live births                 227 non-null    float64
 32  Health: Total expenditure (% of GDP)                        229 non-null    float64
 33  Health: Physicians (per 1000 pop.)                          159 non-null    float64
 34  Education: Government expenditure (% of GDP)                193 non-null    float64
 35  Education: Primary gross enrol. ratio (f/m per 100 pop.)    33 non-null     float64
 36  Education: Secondary gross enrol. ratio (f/m per 100 pop.)  37 non-null     float64
 37  Education: Tertiary gross enrol. ratio (f/m per 100 pop.)   49 non-null     float64
 38  Seats held by women in national parliaments %               229 non-null    float64
 39  Mobile-cellular subscriptions (per 100 inhabitants)         222 non-null    float64
 40  Mobile-cellular subscriptions (per 100 inhabitants).1       228 non-null    float64
 41  Individuals using the Internet (per 100 inhabitants)        229 non-null    int64
 42  Threatened species (number)                                 227 non-null    float64
 43  Forested area (% of land area)                              13 non-null     float64
 44  CO2 emission estimates (million tons/tons per capita)       229 non-null    int64
 45  Energy production, primary (Petajoules)                     229 non-null    int64
 46  Energy supply per capita (Gigajoules)                       20 non-null     float64
 47  Pop. using improved drinking water (urban/rural, %)         21 non-null     float64
 48  Pop. using improved sanitation facilities (urban/rural, %)  220 non-null    float64
 49  Net Official Development Assist. received (% of GNI)        229 non-null    int64
dtypes: float64(40), int64(8), object(2)
memory usage: 89.6+ KB